### PR TITLE
Deal with backslashes in string enum values

### PR DESCRIPTION
**Pull request by plk**
I assume that this is all that's needed?

Closes https://github.com/RSuter/NSwag/issues/1855

### CODE REVIEW

**Comment by RSuter** [comment]
Yes, looks good. What does the @ string verbatim identifier solve?

**Comment by plk** [comment]
Protects the backslashes which end up in there. They need to be preserved correctly as `Value` is used for serialization etc. I will test this in my use case shortly, just to make sure.

**Comment by RSuter** [comment]
Using verbatim string makes sense, but maybe we also need to correctly escape " now?

E.g. 

    [System.Runtime.Serialization.EnumMember(Value = @"{{ enum.Value | "\"", "\"\"" }}")]

(not sure if this works/is allowed)

**Comment by plk** [comment]
Hmm, I suspect we would need to replace:
\" (YAML/JSON double-quote escape) with "" (C# verbatim string double-quote escape).

**Comment by RSuter** [comment]
The Value is already deserialized from a json string to an unescaped c# representation

**Comment by plk** [comment]
Ah, ok, then I'll do a quick test.

**Comment by plk** [comment]
Ok - I have put in some things to deal with double-quotes too. All tests pass and I modified one and added another to check double quote behaviour.

**Comment by plk** [comment]
I could probably test this in my project if I knew which .dll to replace in the NSwag command-line install ...

**Comment by RSuter** [comment]
I don't know if you can just replace the dlls (but probably that works). I think you can just replace the `NJsonSchema.CodeGeneration.CSharp.dll` - the path of the binaries are displayed in the first lines of an CLI execution...

**Pull request merged**
