### PR TITLE
FormatValidators intro, cyclomatic complexity reduced

### PR DESCRIPTION
**Pull request by gandrisl**

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR. Is this just a refactoring of the validator or does it change behavior?

**Comment by gandrisl** [comment]
This just a refactoring. It's a step towards possibility for adding custom validation formats which I plan to add later.

**Comment by RSuter** [comment]
Ok then. Just wondered why you worked on this with no apparent public api/functionality change...

**Comment by RSuter** [comment]
Will do some minor cleanup and merge soon..

**Pull request merged**
