### PR TITLE
CS records

### PR DESCRIPTION
**Pull request by ili**
Some fixies to records after real life usage:
* inheritance fix
* no more default values for records (bad practice from one side, and see below)
* properties in constructor now arranged in alphabetical order - this makes code more stable after refactoring (cleanup for ex) of original code and adding new properties.

Added:
* CS compilation assert for CS code (using Roslyn) 
* default generated namespace set to `System` (needed to pass compilation assert)

### CODE REVIEW

**Comment by ili** [comment]
No problem, that's good! ))

**Comment by RSuter** [comment]
Ok then. Thanks for the pr, will be in annswag release soon.

**Comment by ili** [comment]
Thanks! )

**Comment by RSuter** [comment]
Now live in NSwag, please report any problems... and thanks for the pr! 👍

**Pull request merged**
