### PR TITLE
Do not overwrite existing discriminator property

### PR DESCRIPTION
**Pull request by alb3ric**
Hello,

Is it possible to not overwrite the existing discriminator if it exists ? 
I'm suggesting the following modification.

Best regards

### CODE REVIEW

**Comment by RSuter** [comment]
Why would you declare the property manually in the DTO class? The problem is that it might not behave as expected...

**Comment by alb3ric** [comment]
Hi,

I'm declaring it in the dto class because i want to specify attributes for the discriminator property.
I'm using the generated schema to display a form with json-editor (https://github.com/json-editor/json-editor). I want the property to have a default value but not being display in the form.

**Comment by RSuter** [comment]
I would prefer to not merge this pr and you use a custom schema processor with the SchemaProcessorAttribute to add your additional stuff, defaults etc to the property

**Comment by alb3ric** [comment]
I'm already using a schema processor to add my additional stuff, but the property is then overwrite by GenerateInheritanceDiscriminator

**Comment by RSuter** [comment]
Aren't schema processors executed **after** the schema is generated?

**Comment by alb3ric** [comment]
Oups....sorry for the mistake...
I have started implementing the properties in my dto, then saw it was overwritten, then i did this code modification and then i used the schema processor....forgetting it was executed after....
Sorry again, I'm closing the PR.

**Pull request closed without merging**
