### PR TITLE
Fix: NSwag issue: #1054 - C# Compile Error When Using Negative Enum V…

### PR DESCRIPTION
**Pull request by johnxjcheng**
Hi there, this was an issue that affected my code. I saw your suggestion of fixing. I fixed it and created a test for it. All other tests passed as well.

### CODE REVIEW

**Comment by RSuter** [comment]
I've updated the test and the generator, is this ok for you?

**Comment by johnxjcheng** [comment]
I am fine with most but one: a564839<https://github.com/RSuter/NJsonSchema/commit/a564839bb639bfa301cf2c19394a323adb1b2737>. I commented my reason on the commit.

________________________________

**Comment by RSuter** [comment]
Are the tests broken now? (I cannot checkout your branch (??))

**Comment by RSuter** [comment]
.... tests still look good to me.

**Pull request merged**
