### PR TITLE
add nodatime support out of the box dynamically

### PR DESCRIPTION
**Pull request by MaxDeg**
PR for #459

### CODE REVIEW

**Comment by RSuter** [comment]
I think the test projects do not support PackageReference yet, please add the ref via packages.config

**Comment by MaxDeg** [comment]
did work better .. :(

**Comment by RSuter** [comment]
I fixed it... Thank you for the PR.

**Comment by RSuter** [comment]
Next version of nswag will use this updated version of NJS.

**Comment by MaxDeg** [comment]
Nice ;) 

For the record what was the fix?

**Comment by RSuter** [comment]
Packages added via packages.config also need a dll reference -automatically added by the nuget mgr

**Comment by RSuter** [comment]
Ok it was not that, i also had to fix the build server :)

**Pull request merged**
