### PR TITLE
Bug fix inherited constructor with GenerateConstructorInterface 

### PR DESCRIPTION
**Pull request by thebestnom**
Closes https://github.com/RSuter/NJsonSchema/issues/830

### CODE REVIEW

**Comment by thebestnom** [comment]
Do you need anything else for the PR?

**Comment by thebestnom** [comment]
@RSuter didnt knew about .size, not really an expert in liquid, I will fix everything in next hour or so, thanks!

**Comment by RSuter** [comment]
I still don't understand what this actually solves and why?

**Comment by thebestnom** [comment]
I have my own objects in ts that have the exact same interface as the nswag interfaces, you can follow the issue to see the actual bug, I opened a repo with the minimum repreduce of the bug

**Comment by RSuter** [comment]
So it actually did not generate the constructor code for classes with base classes? So only the base class properties have been copied, correct?

**Comment by thebestnom** [comment]
Exactly

**Comment by thebestnom** [comment]
Why not to merge it?

**Comment by RSuter** [comment]
You closed the PR - not me ;-)

**Comment by RSuter** [comment]
> Exactly

Really strange that someone or me didn't notice that...

**Comment by RSuter** [comment]
Had to fix the tpl: https://github.com/RSuter/NJsonSchema/commit/98a2768e9a2c91f6d58be2c0e338f90b7b217721

**Comment by thebestnom** [comment]
What is the difference? I see the tests are working either way

**Comment by thebestnom** [comment]
Oh, shopify actually doesnt have it and just false/true it always, and the tests doesnt test that?

**Pull request merged**
