### PR TITLE
Add @ symbol to constructor parameters

### PR DESCRIPTION
**Pull request by flipchart**
Fixes issue where parameters are reserved keywords

### CODE REVIEW

**Comment by RSuter** [comment]
Is this a braeking change for non reserved params? Or will the @ be removed by the compiler, intellisense etc if its not needed?

**Comment by flipchart** [comment]
Not a breaking change. You can annotate all params with the @ symbol. In IL the symbol without the @ is always used. Tested it with code I have - doesn't even impact named parameters

**Comment by RSuter** [comment]
I think there is a const list of reserved words somewhere in the code based, we could have used this to change only the required params... :-)

**Comment by flipchart** [comment]
Yeah, that would have produced cleaner output. Makes the template more complex though :) Also, the constructor assignment is done with @ symbols regardless of the name, so if you go the route of only prefixing reserved words, it should be done there as well

**Pull request merged**
