### PR TITLE
Do not overwrite description if previously set

### PR DESCRIPTION
**Pull request by alb3ric**
Related to #550

### CODE REVIEW

**Comment by RSuter** [comment]
Shouldnt it be

    if (p.Description == null) 

and why is it already set? Where? 

I think the problem here is that the description here is the description of the property not the description of the type... The description of the type should be set directly on the type schema itself...

**Comment by RSuter** [comment]
Btw: The tests fail..

**Comment by alb3ric** [comment]
oops sorry my mistake...

You are right it is : if (p.Description == null) 

It is already set in my TypeMapper :

 public async Task GenerateSchemaAsync(JsonSchema4 schema, TypeMapperContext context)
        {
            schema.Type = JsonObjectType.String;
            schema.Description = string.Join(", ", Enum.GetNames(this.MappedType));
        }

**Comment by RSuter** [comment]
Isn't the mapped type referenced here? Is this a primitive type map? Can you provide a little bit more context?

**Comment by alb3ric** [comment]
I'm doing this as a workaround for handling EnumFlags. I'm describing it as a string, because I want it to be display like this in the json-editor I'm using. So I did a TypeMapper like this : 

```
 public class FlaggedEnumTypeMapper : ITypeMapper
    {
        public FlaggedEnumTypeMapper(Type mappedType)
        {
            this.MappedType = mappedType;
        }

        public Type MappedType { get; private set; }

        public bool UseReference => false;

#pragma warning disable 1998
        public async Task GenerateSchemaAsync(JsonSchema4 schema, TypeMapperContext context)
        {
            schema.Type = JsonObjectType.String;
            schema.Description = string.Join(", ", Enum.GetNames(this.MappedType));
        }
    }
```
And I wanted to display in the description the list of possible values of the enum.

**Comment by RSuter** [comment]
9.10.2 soon

**Comment by alb3ric** [comment]
Great, thanks a lot.

**Pull request merged**
