### PR TITLE
Apply ExtensionDataAttributes on Special Types

### PR DESCRIPTION
**Pull request by alb3ric**
Related to issue #548

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR, I've refactored it a little bit so that only one call is needed... ok?

**Comment by alb3ric** [comment]
Ok, great! Thanks 👍 . I just realized that I did the PR with my none github username :s

**Comment by RSuter** [comment]
Sorry, didnt check that... 
Do you need a nuget release of this or are you using the fix with NSwag?

**Comment by alb3ric** [comment]
Yes would be great to have a fix with Nuget. but wait I mite have another request. I'm going to open an issue :)

**Pull request merged**
