### PR TITLE
Ignore Properties Decorated with Attributes from the Ignored Attribute List

### PR DESCRIPTION
**Pull request by dagrooms52**
Adds the type IgnoredPropertyAttributes, which ignores properties decorated with its listed attributes in Json Schema generation.

### CODE REVIEW

**Comment by RSuter** [comment]
Ref https://github.com/RSuter/NJsonSchema/issues/424

**Comment by RSuter** [comment]
Something is wrong with the PR, I see changes from the "master" merge...

**Comment by dagrooms52** [comment]
I'm seeing those changes too. I'm not sure what went wrong, all I did was merge the master branch to fix conflicts.

**Comment by dagrooms52** [comment]
Tried to fix this but ran into a mess of git whitespace issues. Not going to waste more time on whitespace issues. Something is broken in your repo.

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/pull/429

**Pull request closed without merging**
