### PR TITLE
Fix for IntefaceName. @ added to list of invalid chars.

### PR DESCRIPTION
**Pull request by Paul183425**
The @ has been added for compatibility with OData.

### CODE REVIEW

**Comment by RSuter** [comment]
Instead of checking invalidChars, we should use a regex to check if its a valid property literal. I think this one is fine: 

https://stackoverflow.com/a/6671856/876814

`^[a-zA-Z_$][0-9a-zA-Z_$]*$`

**Comment by RSuter** [comment]
error: Regex not found...

https://ci.appveyor.com/project/rsuter/njsonschema-jlw0p/build/1287

**Comment by RSuter** [comment]
Ok now it builds... Thanks

**Comment by Paul183425** [comment]
OK. Thank you very much for dealing with this so quickly.

**Comment by RSuter** [comment]
You're welcome... Ill integrate this into nswag now..

Ref: https://stackoverflow.com/questions/44808003/using-npm-nswag-to-generate-typescript-files-from-swagger-json-files-containing

**Comment by RSuter** [comment]
Ok, the NSwag CI build is available soon with your code changes: 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Pull request merged**
